name: CI for EC2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  SSH:
    name: SSH Git Pull
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Git Pull in EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.WHOOLOOP_FRONT_FOLDER }}
            git reset --hard
            git fetch
            git pull origin main
            yarn install
            yarn build
            pm2 stop viteVue
            pm2 delete viteVue
            pm2 start yarn --name "viteVue" -- preview --host --port 5173
